### ISSUE TITLE
Issue-1-user-can-see-their-car

### ISSUE THREAD

**Issue by PhillipLam89** [PhillipLam89/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Choose an appropriately-sized car image to represent your car
- [x] Choose an appropriate and visually appealing background color as a racetrack
- [x] Fill in any whites-spaces of the car image with the same color as the racetrack
- [x] Make sure the background takes up all spaces possible, no padding nor margins
