### ISSUE TITLE
Issue-2-User-can-turn-car

### ISSUE THREAD

**Issue by PhillipLam89** [PhillipLam89/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create simple data model for which direction the car is facing
- [x] listen for 'keydown' event on the document
- [x] Use CSS transform property to make the car rotate in the direction of the user's arrow key press
- [x] Make sure the car doesn't rotate if it's already facing the same way as the arrow key
- [x] test all functionalities, fix all bugs, and eliminate unnecessary codes
