### ISSUE TITLE
Issue-3-User-can-start-car

### ISSUE THREAD

**Issue by PhillipLam89** [PhillipLam89/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Set an X and Y coordinate for the car inside the data model
- [x] fire an event when the user presses the Space Bar key
- [x] the event should set an interval that repeats every 16 milliseconds
- [x] the interval should increase the X coordinate of the car by a small number 
- [x] use inline style property to move the car to the right
